### ISSUE TITLE
Refactoring items

### ISSUE THREAD

**Issue by shadowwalkersb** [GorgonCryoEM/Gorgon#103]
1. Reduce gui code to minimal
   - [x] Remove all viewers but volume viewer
   - Remove other components that are not essential
     - [x] Themes
     - [x] Plugins
     - [x] Session
   - Modularize into packages
     - [ ] viewer
     - [ ] renderer
     - [ ] surface editor
     - [ ] menus
     - [ ] actions
     - [ ] visualization options
     - [ ] histogram
2. Features
   - [ ] toolbar
   
   ``` python
   toolbar = self.addToolBar('Exit')
   self.toolbar.addAction(exitAction)
   ```
   - [ ] settings: QSettings http://doc.qt.io/qt-4.8/qsettings.html#details
   - [ ] logging
   - [ ] undo/redo
   - [ ] save state #109
   - [ ] debugging
   - [ ] multi-threading (delayedFilter was removed)
   - [ ] coloring (was removed)
   - [ ] ...
3. PyQt/Qt tools/features to consider
   
   ``` python
   QtGui.QIcon
   QtGui.QDesktopWidget().availableGeometry().center()
   
   QtGui.QColorDialog
   QtGui.QFontDialog
   QtGui.QFileDialog
   ```
   - [ ] ToggleButton
   - [ ] CheckBox
   - [ ] Tabbed windows
4. Reduce C++ code to minimal
   - [ ] Modularize into libraries #116 
   - Move computationally expensive and non-gui code into C++ (?)
     - [ ] SSE Correspondence
     - [x] ~~Separate into .h and .cpp #111~~ 
     - [ ] ...
5. - [ ] **Documentation**
6. Folder and class hierarchies #97
   - [ ] window_manager, camera, volume_viewer ... #105 
   - [ ] Rename *form into class and file Form in their appropriate package (?)
   - [ ] UI forms and files #104
7. Scribbles
   -  #107 , #101

**Comment by shadowwalkersb** [comment]
No further refactoring. Closing.
