### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by shadowwalkersb** [GorgonCryoEM/Gorgon#28]
- [ ] Repo
  - [x] Labels, milestones #30 
  - [x] Branches, ~~#23, #35, #33 , #37~~ 
  - [ ] External Libraries [repo](../../ExternalLibraries), #19
    - [ ] Consider using --rejoin option #36
  - [ ] including-a-github-wiki-in-a-repository-as-a-submodule, [maybe with `subtree` instead of <s>`submodules`](http://brendancleary.com/2013/03/08/including-a-github-wiki-in-a-repository-as-a-submodule/)</s>
  - [ ] Workflow #20
  - [ ] Wiki & README #36, #12, ~~#4~~, ~~#31~~, ~~#8~~
- [ ] Separate scripts #44 
- [ ] [Build Milestone](../milestones/Build/v2.2), #1, #5, #13
  - [ ] CMake (issue #43 )
  - [ ] Mac (issue #15 )
    - [ ] 64 bit
  - [ ] Windows (issue #3 )
    - [ ] 64 bit
    - [x] 32 bit
  - [ ] Linux (issue #16 )
    - [ ] 64 bit
    - [ ] 32 bit
  - [ ] Distribution/Deployment (#1, #13, #26, ~~#34~~, #9, #10, ~~#40~~ )
- [ ] Refactor
  - [ ] Test cases, scripts, unit testing #39 
  - [ ] External Libraries #19, #5, #6, #36
    - [ ] Cleanup unnecessary libraries and files
    - [ ] Versions #19, #22
  - [ ] Separate core & explorer, toolkit
  - [ ] Modularize targets
  - [ ] Prioritize targets
- [ ] Tutorials, guides #7
  - [ ] Git #20
  - [ ] GitHub ([some material in Wiki](../wiki/TODO,-explore,-evaluate,-scribbles#explore--evaluate))

**Comment by shadowwalkersb** [comment]
Hard to maintain, issues when organized into milestones and labeled already serve the similar purpose. Closing.
