### ISSUE TITLE
Refactor CMakeLists.txt to work for all platforms

### ISSUE THREAD

**Issue by shadowwalkersb** [GorgonCryoEM/Gorgon#43]
- [x] Check *.cmake files for hardcoded values
- [x] ~~Add dynamic target to handle external lib builds automatically instead of the user having to select an option.~~ Dynamic target idea is very hard, if possible at all, to implement in a straight forward way. Dropping it.
- [x] Evaluate when `find_package` should be called in *.cmake files. Or, maybe, completely remove `find_package` and have `find_path & find_library` do the search and assign the results into our own variables named in a more consistent way, `proj_libraries & proj_includes`.
- [x] Add md5/sha1 checks for the packages that provide them
- [x] Install step
  - [x] rename target install to **package** and have install copy libpyGORGON ~~into python~~
  - [x] move SIP, PyQt4 to install step. They are not build dependencies.
  - [x] install Python dependencies via pip
  - [x] Rename install components and their corresponding targets
- [x] Boost install_name, #72 
- [x] Cleanup GLUT, #52 
- [x] Packaging step
- [x] ~~Refactor debugging~~

---
- [x] ~~Add a PATHNAME for downloaded and extracted files to avoid downloading and extracting over and over again~~
- [x] ~~Modularize dependency handling~~
- [x] ~~Add CMakeLists to ExternalLibraries to handle external library builds?~~
- [x] ~~ExternalProject_Add vs add_subdirectories ?~~
  - http://www.cmake.org/pipermail/cmake/2013-February/053429.html and following replies
  - https://github.com/OpenChemistry/openchemistry, an example of **super build**
  - http://stackoverflow.com/questions/17446981/cmake-externalproject-add-and-findpackage?lq=1~~

---
- [x] Python #79
- [x] Boost #50, #55 
- [x] FFTW #51 
- [x] OpenGL/GLUT #52 
- [x] ~~Packaging~~ moved to #61 
  - http://www.jeffknupp.com/blog/2013/08/16/open-sourcing-a-python-project-the-right-way/
- [x] ~~Platform Checks #60~~ moved to milestone Refactor
- [x] A whole tutorial, read before closing this issue
  - http://rachid.koucha.free.fr/tech_corner/cmake_manual.html

More links in the [wiki](../wiki/Reference-Links-to-Read#cmake).

/cc Wiki
/cc #15 , #3 , #16
