### ISSUE TITLE
TODO/FIXME items in Gorgon code

### ISSUE THREAD

**Issue by shadowwalkersb** [GorgonCryoEM/Gorgon#62]
- [ ] TODO <--------- FIX THIS (last paramater)                         [Gorgon/FlexibleFittingEngine.h#L163](/GorgonCryoEM/Gorgon/blob/master/Gorgon/FlexibleFittingEngine.h#L163)
- [ ] TODO Also normalize the sheet capacity here?                      [GraphMatch/WongMatch15ConstrainedNoFuture.h#L1320](/GorgonCryoEM/Gorgon/blob/master/GraphMatch/WongMatch15ConstrainedNoFuture.h#L1320)
- [ ] TODO Ask Matt if I correctly handled cases where apix_x != apix_y or apix_x != apix_z     [ProteinMorph/SSEHunter.h#L773](/GorgonCryoEM/Gorgon/blob/master/ProteinMorph/SSEHunter.h#L773)
- [ ] TODO check if the cast for mapSize is the way to go                   [ProteinMorph/SSEHunter.h#L620](/GorgonCryoEM/Gorgon/blob/master/ProteinMorph/SSEHunter.h#L620)
- [ ] TODO Consider case where this voxel may have already been visited but with a longer path  [GraphMatch/SkeletonReader.h#L882](/GorgonCryoEM/Gorgon/blob/master/GraphMatch/SkeletonReader.h#L882)
- [ ] TODO Finish coding SetGeometryScores                          [ProteinMorph/SSEHunter.h#L79](/GorgonCryoEM/Gorgon/blob/master/ProteinMorph/SSEHunter.h#L79)
- [ ] TODO Finish coding the geometry score portion of this function                [ProteinMorph/SSEHunter.h#L66](/GorgonCryoEM/Gorgon/blob/master/ProteinMorph/SSEHunter.h#L66)
- [ ] TODO finish this function                                 [ProteinMorph/SSEHunter.h#L376](/GorgonCryoEM/Gorgon/blob/master/ProteinMorph/SSEHunter.h#L376)
- [ ] TODO fix                                          [GraphMatch/SSECorrespondenceResult.h#L86](/GorgonCryoEM/Gorgon/blob/master/GraphMatch/SSECorrespondenceResult.h#L86)
- [ ] TODO Fix patthernLength and baseLength for sheet-to-sheet case.               [GraphMatch/WongMatch15ConstrainedNoFuture.h#L437](/GorgonCryoEM/Gorgon/blob/master/GraphMatch/WongMatch15ConstrainedNoFuture.h#L437)
- [ ] TODO Fix this:                                        [GraphMatch/Matcher6.h#L259](/GorgonCryoEM/Gorgon/blob/master/GraphMatch/Matcher6.h#L259)
- [ ] TODO Fix, has bug. But getting closer.                            [GraphMatch/WongMatch15ConstrainedNoFuture.h#L480](/GorgonCryoEM/Gorgon/blob/master/GraphMatch/WongMatch15ConstrainedNoFuture.h#L480)
- [ ] TODO Fix!                                         [Gorgon/SSECorrespondenceEngine.h#L133](/GorgonCryoEM/Gorgon/blob/master/Gorgon/SSECorrespondenceEngine.h#L133)
- [ ] TODO Fix! 0 not acceptable!                               [Gorgon/SSECorrespondenceEngine.h#L123](/GorgonCryoEM/Gorgon/blob/master/Gorgon/SSECorrespondenceEngine.h#L123)
- [ ] TODO If a vertex is part of both the sheet skeleton and the helix skeleton, typeCost = 0; [ProteinMorph/SSEHunter.h#L240](/GorgonCryoEM/Gorgon/blob/master/ProteinMorph/SSEHunter.h#L240)
- [ ] TODO In EMAN1 the maximum distance is sqrt(3*4                        [ProteinMorph/SSEHunter.h#L220](/GorgonCryoEM/Gorgon/blob/master/ProteinMorph/SSEHunter.h#L220)
- [ ] TODO Is this the same as testing if it's in the sheet skeleton                [ProteinMorph/SSEHunter.h#L241](/GorgonCryoEM/Gorgon/blob/master/ProteinMorph/SSEHunter.h#L241)
- [ ] TODO looks like the following line just returns a single corner for the helix         [GraphMatch/StandardGraph.h#L349](/GorgonCryoEM/Gorgon/blob/master/GraphMatch/StandardGraph.h#L349)
- [ ] TODO looks like the following line just returns a single corner for the helix         [GraphMatch/StandardGraph.h#L360](/GorgonCryoEM/Gorgon/blob/master/GraphMatch/StandardGraph.h#L360)
- [ ] TODO Make it work with helices                                [ProteinMorph/SSEHunter.h#L873](/GorgonCryoEM/Gorgon/blob/master/ProteinMorph/SSEHunter.h#L873)
- [ ] TODO Make this better!!                                   [GraphMatch/Matcher7.h#L253](/GorgonCryoEM/Gorgon/blob/master/GraphMatch/Matcher7.h#L253)
- [ ] TODO Make this more accurate                              [GraphMatch/LedaMatch.h#L78](/GorgonCryoEM/Gorgon/blob/master/GraphMatch/LedaMatch.h#L78)
- [ ] TODO Make this more accurate                              [GraphMatch/Matcher6.h#L98](/GorgonCryoEM/Gorgon/blob/master/GraphMatch/Matcher6.h#L98)
- [ ] TODO Make this more accurate                              [GraphMatch/Matcher7.h#L108](/GorgonCryoEM/Gorgon/blob/master/GraphMatch/Matcher7.h#L108)
- [ ] TODO Make this more accurate                              [GraphMatch/VFInexact.h#L94](/GorgonCryoEM/Gorgon/blob/master/GraphMatch/VFInexact.h#L94)
- [ ] TODO Make this more accurate                              [GraphMatch/VFMatch.h#L86](/GorgonCryoEM/Gorgon/blob/master/GraphMatch/VFMatch.h#L86)
- [ ] TODO Make this more accurate                              [GraphMatch/WongMatch.h#L104](/GorgonCryoEM/Gorgon/blob/master/GraphMatch/WongMatch.h#L104)
- [ ] TODO Make this more accurate                              [GraphMatch/WongMatch15.h#L109](/GorgonCryoEM/Gorgon/blob/master/GraphMatch/WongMatch15.h#L109)
- [ ] TODO Make this more accurate                              [GraphMatch/WongMatch15Constrained.h#L110](/GorgonCryoEM/Gorgon/blob/master/GraphMatch/WongMatch15Constrained.h#L110)
- [ ] TODO Make this more accurate                              [GraphMatch/WongMatch15ConstrainedOnlyA.h#L109](/GorgonCryoEM/Gorgon/blob/master/GraphMatch/WongMatch15ConstrainedOnlyA.h#L109)
- [ ] TODO Make this more accurate                              [GraphMatch/WongMatch15Ordered.h#L107](/GorgonCryoEM/Gorgon/blob/master/GraphMatch/WongMatch15Ordered.h#L107)
- [ ] TODO Make this more accurate                              [GraphMatch/WongMatch2.h#L125](/GorgonCryoEM/Gorgon/blob/master/GraphMatch/WongMatch2.h#L125)
- [ ] TODO Make this more accurate                              [GraphMatch/WongMatchMissing.h#L100](/GorgonCryoEM/Gorgon/blob/master/GraphMatch/WongMatchMissing.h#L100)
- [ ] TODO Make this more accurate                              [GraphMatch/WongMatchMissing15.h#L105](/GorgonCryoEM/Gorgon/blob/master/GraphMatch/WongMatchMissing15.h#L105)
- [ ] TODO Make this more accurate                              [GraphMatch/WongMatchMissing15Linked.h#L109](/GorgonCryoEM/Gorgon/blob/master/GraphMatch/WongMatchMissing15Linked.h#L109)
- [ ] TODO possibly implement mouse picking using ray intersection              [Gorgon/CAlphaRenderer.h#L214](/GorgonCryoEM/Gorgon/blob/master/Gorgon/CAlphaRenderer.h#L214)
- [ ] TODO possibly implement mouse picking using ray intersection              [Gorgon/CAlphaRenderer.h#L329](/GorgonCryoEM/Gorgon/blob/master/Gorgon/CAlphaRenderer.h#L329)
- [ ] TODO possibly implement mouse picking using ray intersection              [Gorgon/CAlphaRenderer.h#L1014](/GorgonCryoEM/Gorgon/blob/master/Gorgon/CAlphaRenderer.h#L1014)
- [ ] TODO possibly implement mouse picking using ray intersection              [Gorgon/CAlphaRenderer.h#L1093](/GorgonCryoEM/Gorgon/blob/master/Gorgon/CAlphaRenderer.h#L1093)
- [ ] TODO possibly implement mouse picking using ray intersection              [Gorgon/CAlphaRenderer.h#L1383](/GorgonCryoEM/Gorgon/blob/master/Gorgon/CAlphaRenderer.h#L1383)
- [ ] TODO read file by small chunks, combine in one large string               [ExternalLibraries/alglib/ap.h#L1081](/GorgonCryoEM/ExternalLibraries/blob/master/alglib/ap.h#L1081)
- [ ] TODO Remove this arbitrary weight!                            [GraphMatch/WongMatch15ConstrainedNoFuture.h#L575](/GorgonCryoEM/Gorgon/blob/master/GraphMatch/WongMatch15ConstrainedNoFuture.h#L575)
- [ ] TODO Scale the sheet size by the geometric scale factor to make units match       [GraphMatch/SkeletonReader.h#L349](/GorgonCryoEM/Gorgon/blob/master/GraphMatch/SkeletonReader.h#L349)
- [ ] TODO TEST                                         [ProteinMorph/SSEHunter.h#L600](/GorgonCryoEM/Gorgon/blob/master/ProteinMorph/SSEHunter.h#L600)
- [ ] TODO TEST                                         [ProteinMorph/SSEHunter.h#L747](/GorgonCryoEM/Gorgon/blob/master/ProteinMorph/SSEHunter.h#L747)
- [ ] TODO TEST                                         [ProteinMorph/SSEHunter.h#L766](/GorgonCryoEM/Gorgon/blob/master/ProteinMorph/SSEHunter.h#L766)
- [ ] TODO Test this function!!!!                               [ProteinMorph/SSEHunter.h#L659](/GorgonCryoEM/Gorgon/blob/master/ProteinMorph/SSEHunter.h#L659)
- [ ] TODO test whether in the helix skeleton                           [ProteinMorph/SSEHunter.h#L243](/GorgonCryoEM/Gorgon/blob/master/ProteinMorph/SSEHunter.h#L243)
- [ ] TODO throw an exception                                   [ProteinMorph/SSEHunter.h#L409](/GorgonCryoEM/Gorgon/blob/master/ProteinMorph/SSEHunter.h#L409)
- [ ] XXX test for "small" instead                              [ProteinMorph/CurveDeformer.h#L512](/GorgonCryoEM/Gorgon/blob/master/ProteinMorph/CurveDeformer.h#L512)

/src_py
- [ ] TODO: check on whether the current match is a helix or a strand                                                                             [Gorgon/src_py/calpha_structure_editor.py#L1085              ](/GorgonCryoEM/Gorgon/blob/master/Gorgon/src_py/calpha_structure_editor.py#L1085)
- [ ] TODO: Move this color changing code somewhere else                                                                                          [Gorgon/src_py/sse_helix_correspondence_finder_form.py#L1062 ](/GorgonCryoEM/Gorgon/blob/master/Gorgon/src_py/sse_helix_correspondence_finder_form.py#L1062)
- [ ] TODO: only count strands that are different. every sheet must be the same color!                                                            [Gorgon/src_py/sse_helix_correspondence_finder_form.py#L951  ](/GorgonCryoEM/Gorgon/blob/master/Gorgon/src_py/sse_helix_correspondence_finder_form.py#L951)
- [ ] TODO: figure out how to handle orphan strands                                                                                               [Gorgon/src_py/seq_model/Chain.py#L888                       ](/GorgonCryoEM/Gorgon/blob/master/Gorgon/src_py/seq_model/Chain.py#L888)
- [ ] TODO: Mike this raises an error!;                                                                                                           [Gorgon/src_py/sse_helix_correspondence_finder_form.py#L791  ](/GorgonCryoEM/Gorgon/blob/master/Gorgon/src_py/sse_helix_correspondence_finder_form.py#L791)
- [ ] TODO: This method can be refactored using the chain.secels dictionary... this would stop the need to search for previous and next helices.. [Gorgon/src_py/calpha_flexible_fitting_form.py#L504          ](/GorgonCryoEM/Gorgon/blob/master/Gorgon/src_py/calpha_flexible_fitting_form.py#L504)
- [ ] TODO: make sure this will not eventually overwrite chain IDs from a PDB file that doesn't start at A.                                       [Gorgon/src_py/seq_model/Chain.py#L335                       ](/GorgonCryoEM/Gorgon/blob/master/Gorgon/src_py/seq_model/Chain.py#L335)
- [ ] TODO: Add a test for input of *.seq files                                                                                                   [Gorgon/src_py/seq_model/SeqModelTests.py#L205               ](/GorgonCryoEM/Gorgon/blob/master/Gorgon/src_py/seq_model/SeqModelTests.py#L205)
- [ ] TODO: find a more elegant way than dividing radius by the apix_X to fix the scaling problem                                                 [Gorgon/src_py/calpha_structure_editor.py#L125               ](/GorgonCryoEM/Gorgon/blob/master/Gorgon/src_py/calpha_structure_editor.py#L125)
- [ ] TODO: We need to figure out how to handle this exception                                                                                    [Gorgon/src_py/seq_model/Chain.py#L106                       ](/GorgonCryoEM/Gorgon/blob/master/Gorgon/src_py/seq_model/Chain.py#L106)
- [ ] TODO:We might want to modify this to use any unused numbers (after a rename)                                                                [Gorgon/src_py/seq_model/Chain.py#L102                       ](/GorgonCryoEM/Gorgon/blob/master/Gorgon/src_py/seq_model/Chain.py#L102)
- [ ] TODO: Put a error message here telling the user that the save failed                                                                        [Gorgon/src_py/volume_sse_builder_form.py#L63                ](/GorgonCryoEM/Gorgon/blob/master/Gorgon/src_py/volume_sse_builder_form.py#L63)
- [ ] TODO: perhaps we should change this behavior, in case someone modified a chain object then imported a PDB with a chain of the same name     [Gorgon/src_py/seq_model/Chain.py#L59                        ](/GorgonCryoEM/Gorgon/blob/master/Gorgon/src_py/seq_model/Chain.py#L59)

/cc PR #106

**Comment by shadowwalkersb** [comment]
@GorgonCryoEM/developers 
There are some (!) TODO comments in the code. They are listed in the description above. Every item has a description and a link which should take you directly to the line where the item is. Can check the ones that have been fixed and are not relevant any more?

**Comment by shadowwalkersb** [comment]
Dropping.
